version: '3.1'

services:

 reserve:
    image: reserve
    ports:
      - "8000:8000"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"